import type { Metadata } from "next";
import { Exo_2, Lexend_Exa } from "next/font/google";
import "./globals.css";
import { Account, Navigation } from "@component/src/components/navbar";

const Exo2 = Exo_2({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const LexendExa = Lexend_Exa({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Exo2.variable} ${LexendExa.variable} antialiased`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
